### PR TITLE
Dynamic cards & Popup window

### PR DESCRIPTION
**Pull request by DaveZag**
# Dynamic cards and Popup Window
## In this branch we:
- Refactor the entire work section content using Javascript.
- Add markup for the Popup window and style the content.
- Display the Popup each time a __"See project"__ button is clicked.
- Ignore all unecessary files in .gitignore.

.

### CODE REVIEW

**Review by Ismailco — COMMENTED** [review]
Hi @DaveZag, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is not using peer programing, all students in the group should commit to this PR

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by DaveZag** [comment]
What if my coding partner has decided to not work on this project since he wants to repeat the week and understand better javascript concepts?🤔

**Comment by Ismailco** [comment]
@DaveZag, I think you can contact student success for that matter

**Review by Ismailco — APPROVED** [review]
### Hi @DaveZag, @SaboorSohaib, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

cr-approve


## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
